/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jycykj.gui;

import com.jycykj.dao.ComponentDao;
import com.jycykj.dao.ProcedureDao;
import com.jycykj.tables.ComponentManagerTableModel;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author xuqin
 */
public class ComponentProcedureSelectDialog extends javax.swing.JDialog {
    private JTable componentManagerTable;
    private String componentId = null;                     //选中的零件标号
    private int modifiedIndex=-1;                             //正在修改工序的行
    private List<Integer> preModifiedProcedureIds = null;   //修改之前该零件的工序号集合   
    private List<Integer> postModifiedProcedureIds = null;  //修改之后该零件的工序号集合
    
    private List<String> initialNotSelectedProcedureNames = null;     //初始化的未选择的工序名称
    private List<String> initialSelectedProcedureNames = null;       //初始化的选择的工序名称
    //private List<String> allProcedureNames = null;
    
    private Map<String,Integer> procedureNameIdMaps = null;
    private Map<Integer,String> procedureIdNameMaps = null;
    
    private ComponentDao componentDao = ComponentDao.getInstance();
    private ProcedureDao procedureDao = ProcedureDao.getInstance();
    /**
     * Creates new form ComponentProcedureSelectDialog
     */
    public ComponentProcedureSelectDialog(java.awt.Frame parent, boolean modal,JTable componentManagerTable,String componentId,int modifiedIndex) {
        super(parent, modal);
        this.componentId = componentId;
        this.componentManagerTable = componentManagerTable;
        this.modifiedIndex=modifiedIndex;
        procedureNameIdMaps = procedureDao.getProceduresMap();
        procedureIdNameMaps = getProcedureIdNameMaps();
        
        //--------------------------------设置初始的右框内容-----------------------------
        initialSelectedProcedureNames = componentDao.getProcedureNames(this.componentId);
        
        //--------------------------------设置初始的左框内容------------------------------
        initialNotSelectedProcedureNames = new ArrayList<String>(procedureNameIdMaps.keySet());
        initialNotSelectedProcedureNames.removeAll(initialSelectedProcedureNames);
        
        //--------------------------------设置初始零件的工序号-----------------------------
        preModifiedProcedureIds = getProcedureIds();
        postModifiedProcedureIds = new ArrayList<Integer>(preModifiedProcedureIds);
        myprint(postModifiedProcedureIds);
        initComponents();
    }
    
    private List<Integer> getProcedureIds() {
        List<Integer> result = new ArrayList<Integer>();
        for(String procedure_name : initialSelectedProcedureNames) {
            if(procedureNameIdMaps.containsKey(procedure_name)) {
                result.add(procedureNameIdMaps.get(procedure_name));
            }
        }
        return result;
    }
    
    private Map<Integer, String> getProcedureIdNameMaps() {
        Map<Integer,String> map = new HashMap<Integer, String>();
        for(String name : procedureNameIdMaps.keySet()) {
            map.put(procedureNameIdMaps.get(name),name);
        }
        return map;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        notSelectedList = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        selectedList = new javax.swing.JList();
        jPanel4 = new javax.swing.JPanel();
        removeButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "工序选择框", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("宋体", 0, 18))); // NOI18N

        DefaultListModel notSelectedListModel = new DefaultListModel();
        for(String name : initialNotSelectedProcedureNames) {
            notSelectedListModel.addElement(name);
        }
        notSelectedList.setModel(notSelectedListModel);
        jScrollPane1.setViewportView(notSelectedList);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        DefaultListModel selectedListModel = new DefaultListModel();
        for(String name : initialSelectedProcedureNames) {
            selectedListModel.addElement(name);
        }
        selectedList.setModel(selectedListModel);
        jScrollPane2.setViewportView(selectedList);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        removeButton.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        removeButton.setText("<<");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        addButton.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        addButton.setText(">>");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        saveButton.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        saveButton.setText("保存");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(removeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(addButton)
                .addGap(18, 18, 18)
                .addComponent(removeButton)
                .addGap(98, 98, 98)
                .addComponent(saveButton)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel1.setText("未选工序");

        jLabel2.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel2.setText("已选工序");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        addItem();
    }//GEN-LAST:event_addButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // TODO add your handling code here:
        removeItem();
    }//GEN-LAST:event_removeButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        
        String confirmString = getConfirmString();    //确认信息（删除和添加工序的详细信息）
        int choice = JOptionPane.showConfirmDialog(this,"你确定执行下列操作吗？\n\n" + confirmString,"警告",JOptionPane.WARNING_MESSAGE);
        if(choice==JOptionPane.YES_OPTION) {
            //-------------------------更改数据库操作-----------------------------------
            List<String> procedureList = new ArrayList<String>();
            procedureList.add("a");
            
            System.out.println("In dialog : " + componentManagerTable);
            
            //componentManagerTable.setModel(componentManagerTable.getModel().setValueAt(procedures, modifiedIndex, 5));
            ((ComponentManagerTableModel)componentManagerTable.getModel()).getComponentList().get(modifiedIndex).setProcedures(procedureList);
            ((ComponentManagerTableModel)componentManagerTable.getModel()).fireTableCellUpdated(modifiedIndex,5);
            
            this.dispose();
        }
    }//GEN-LAST:event_saveButtonActionPerformed
    
    public String getConfirmString() {
        StringBuilder confirmString = new StringBuilder();
        List<Integer> preModifiedProcedureIdsCopy = new ArrayList<Integer>(preModifiedProcedureIds);
        List<Integer> postModifiedProcedureIdsCopy = new ArrayList<Integer>(postModifiedProcedureIds);
        
        postModifiedProcedureIdsCopy.removeAll(preModifiedProcedureIds);
        for(int id : postModifiedProcedureIdsCopy) {
            confirmString.append("添加工序 : " + procedureIdNameMaps.get(id) + "\n");
        }
        
        postModifiedProcedureIdsCopy =  new ArrayList<Integer>(postModifiedProcedureIds);   //还原
        preModifiedProcedureIdsCopy.removeAll(postModifiedProcedureIdsCopy);
        for(int id : preModifiedProcedureIdsCopy) {
            confirmString.append("删除工序 : " + procedureIdNameMaps.get(id) + "\n");
        }
        return confirmString.toString();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComponentProcedureSelectDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComponentProcedureSelectDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComponentProcedureSelectDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComponentProcedureSelectDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ComponentProcedureSelectDialog dialog = new ComponentProcedureSelectDialog(new javax.swing.JFrame(), true,null,"",1);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    void myprint(List<Integer> list) {
        for(int i : list) {
            System.out.print(i+ " ");
        }
        System.out.println();
    }
    
     /**
        * 添加项（left->right）
        */
       private void addItem() {
              if (notSelectedList.getSelectedIndex() != -1) {
                     Object o = notSelectedList.getSelectedValue();
                     ((DefaultListModel) notSelectedList.getModel()).remove(notSelectedList.getSelectedIndex());
                     ((DefaultListModel) selectedList.getModel()).addElement(o);
                     postModifiedProcedureIds.add(procedureNameIdMaps.get(o));
                     myprint(postModifiedProcedureIds);
              }
       }
 
       /**
        * 删除项(right->left)
        */
       private void removeItem() {
              if (selectedList.getSelectedIndex() != -1) {
                     Object o = selectedList.getSelectedValue();
                     ((DefaultListModel) selectedList.getModel()).remove(selectedList.getSelectedIndex());
                     ((DefaultListModel) notSelectedList.getModel()).addElement(o);
                      postModifiedProcedureIds.remove(procedureNameIdMaps.get(o));
                      myprint(postModifiedProcedureIds);
              }
       }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList notSelectedList;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JList selectedList;
    // End of variables declaration//GEN-END:variables

 

}
