/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jycykj.gui;

import com.jycykj.helper.ImageIconUtil;
import com.jycykj.tables.ComponentProcedureTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTextField;
import net.sourceforge.jdatepicker.JDateComponentFactory;
import net.sourceforge.jdatepicker.JDatePanel;
import net.sourceforge.jdatepicker.impl.UtilDateModel;

/**
 *
 * @author xuqin
 */
public class ProduceCardDatePickerDialog extends javax.swing.JDialog {
    
    public ProduceCardDatePickerDialog(java.awt.Frame parent, boolean modal,final ComponentProcedureTableModel componentProcedureTableModel,final int selectRow,int screen_x, int screen_y) {
        super(parent, modal);
        final JDatePanel jp = JDateComponentFactory.createJDatePanel(new UtilDateModel(new Date()));
        jp.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e)
            {
                try{
                    System.out.println(new SimpleDateFormat("yyyy-MM-dd").format(jp.getModel().getValue()));
                    
                    componentProcedureTableModel.getWorks().get(selectRow).setDate((Date)jp.getModel().getValue());
                    componentProcedureTableModel.fireTableRowsUpdated(selectRow, selectRow);
                 //如果选中日期后，想消除JDialog，那么jp.addActionListener（new一个ActionListener的实现类，将this对象传递进去）然后调用dispose()方法
                }catch(Exception ex){
                    //该日期控件点击Clear的时候会出异常，因为没有选中日期，如果要消除该异常，那么直接导入源代码，在源码里面改动。
                    //这里直接简化操作，点击Clear出现异常，直接将jtextfield赋值为""
                    componentProcedureTableModel.getWorks().get(selectRow).setDate(null);
                    componentProcedureTableModel.fireTableRowsUpdated(selectRow, selectRow);
                }
            }
        });
        JPanel jpanel =(JPanel)jp;
        this.add(jpanel);
        this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        this.setBounds(screen_x, screen_y, 350, 300);
        this.setTitle("请选择日期");
        this.setIconImage(ImageIconUtil.getFrameIcon("pics/datepicker.png"));
    }
    
    
       public ProduceCardDatePickerDialog(java.awt.Frame parent, boolean modal,final JTextField textField ,int screen_x, int screen_y) {
        super(parent, modal);
        final JDatePanel jp = JDateComponentFactory.createJDatePanel(new UtilDateModel(new Date()));
        jp.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e)
            {
                try{
                    System.out.println(new SimpleDateFormat("yyyy-MM-dd").format(jp.getModel().getValue()));
                    textField.setText(new SimpleDateFormat("yyyy-MM-dd").format(jp.getModel().getValue()));
                 //如果选中日期后，想消除JDialog，那么jp.addActionListener（new一个ActionListener的实现类，将this对象传递进去）然后调用dispose()方法
                }catch(Exception ex){
                    //该日期控件点击Clear的时候会出异常，因为没有选中日期，如果要消除该异常，那么直接导入源代码，在源码里面改动。
                    //这里直接简化操作，点击Clear出现异常，直接将jtextfield赋值为""
                    textField.setText("");
                }
            }
        });
        JPanel jpanel =(JPanel)jp;
        this.add(jpanel);
        this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        this.setBounds(screen_x, screen_y, 350,300);
        this.setTitle("请选择日期");
        this.setIconImage(ImageIconUtil.getFrameIcon("pics/datepicker.png"));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProduceCardDatePickerDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProduceCardDatePickerDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProduceCardDatePickerDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProduceCardDatePickerDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProduceCardDatePickerDialog dialog = new ProduceCardDatePickerDialog(new javax.swing.JFrame(),true,null,0,0,0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
